[package]
name = "rust-amiga-emul"
version = "0.1.0"
authors = ["Krister Jansson <krustur@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.3"
rand = "0.3"
byteorder = "1.3.4"
num-traits = "0.2"
num-derive = "0.2"