; ----------------------T----------------------------------

; Path: ..\ami-test-runner\src\tests\addi.s
; This file is autogenerated

 ;rts in case this source is run by mistake
 rts

;===========================================

addi_byte_immediate_data_to_data_register_direct
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_byte_immediate_data_to_data_register_direct",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$00004321
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $06,$07,$00,$23

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$00004344
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 ADDI.B #$23,D7

;===========================================

addi_byte_immediate_data_to_absolute_short
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_byte_immediate_data_to_absolute_short",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000001,$00004000,.arrange_mem_00004000
 dc.l $00000000

.arrange_mem_00004000
 dc.b $4C
 even

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$0000d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000003,$00040000
 dc.b $06,$38,$00,$38,$40,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000001,$00004000,.assert_mem_00004000
 dc.l $00000000

.assert_mem_00004000
 dc.b $84
 even

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$0000d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040006 ; PC
 dc.w $000a ; SR=-N-O-

.assert_code
 ADDI.B #$38,($4000).W

;===========================================

addi_word_immediate_data_to_data_register_direct
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_word_immediate_data_to_data_register_direct",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$00004321
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $06,$47,$12,$34

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$00005555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 ADDI.W #$1234,D7

;===========================================

addi_word_immediate_data_to_absolute_long
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_word_immediate_data_to_absolute_long",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000002,$00040000,.arrange_mem_00040000
 dc.l $00000000

.arrange_mem_00040000
 dc.b $3C,$09

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000004,$00030000
 dc.b $06,$79,$38,$78,$00,$04,$00,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000002,$00040000,.assert_mem_00040000
 dc.l $00000000

.assert_mem_00040000
 dc.b $74,$81

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $000000d0,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00030008 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 ADDI.W #$3878,($00040000).L

;===========================================

addi_long_immediate_data_to_data_register_direct
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_long_immediate_data_to_data_register_direct",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $10101010,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000003,$00030000
 dc.b $06,$80,$76,$85,$76,$85

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $86958695,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00030006 ; PC
 dc.w $000a ; SR=-N-O-

.assert_code
 ADDI.L #$76857685,D0

;===========================================

addi_long_immediate_data_to_absolute_long
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "addi_long_immediate_data_to_absolute_long",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000004,$00040000,.arrange_mem_00040000
 dc.l $00000000

.arrange_mem_00040000
 dc.b $EC,$09,$00,$01

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $86958695,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000005,$00030000
 dc.b $06,$B9,$38,$78,$45,$45,$00,$04,$00,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000004,$00040000,.assert_mem_00040000
 dc.l $00000000

.assert_mem_00040000
 dc.b $24,$81,$45,$46

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $86958695,$000000d1,$000000d2,$000000d3,$000000d4,$000000d5,$000000d6,$dddd5555
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $0003000a ; PC
 dc.w $0011 ; SR=E---C

.assert_code
 ADDI.L #$38784545,($00040000).L

