; ----------------------T----------------------------------

; Path: ..\ami-test-runner\src\tests\divs.s
; This file is autogenerated

 ;rts in case this source is run by mistake
 rts

;===========================================

divs_w__data_register_by_ea__x_unaffected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__x_unaffected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000002,$00008000,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $83,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000002,$00004000,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 DIVS.W D0,D1

;===========================================

divs_w__data_register_by_ea__x_unaffected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__x_unaffected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000002,$0fff8000,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $83,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000002,$0fff8000,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0002 ; SR=---O-

.assert_code
 DIVS.W D0,D1

;===========================================

divs_w__data_register_by_ea__n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$000001c2,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $0007 ; --ZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $83,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$0000fffd,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 DIVS.W D0,D1

;===========================================

divs_w__data_register_by_ea__n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$ffffff6a,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $83,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$00000001,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 DIVS.W D0,D1

;===========================================

divs_w__data_register_by_ea__z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$00000000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000b ; -N-OC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8F,$FC,$12,$34

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$00000000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 DIVS.W #$1234,D7

;===========================================

divs_w__data_register_by_ea__z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$00005678
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8F,$FC,$12,$34

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$0da80004
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 DIVS.W #$1234,D7

;===========================================

divs_w__data_register_by_ea__v_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__v_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$56780000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $001d ; ENZ-C

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8F,$FC,$12,$34

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$56780000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0012 ; SR=E--O-

.assert_code
 DIVS.W #$1234,D7

;===========================================

divs_w__data_register_by_ea__v_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divs_w__data_register_by_ea__v_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$00056780
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8F,$FC,$82,$34

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $0000ff6a,$d1d1d1d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$7d88fff6
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0018 ; SR=EN---

.assert_code
 DIVS.W #$8234,D7

