; ----------------------T----------------------------------

; Path: ..\ami-test-runner\src\tests\divu.s
; This file is autogenerated

 ;rts in case this source is run by mistake
 rts

;===========================================

divu_w_x_not_affected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_x_not_affected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000002,$00030000,.arrange_mem_00030000
 dc.l $00000000

.arrange_mem_00030000
 dc.b $00,$05

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $8A,$D5

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00010033,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 DIVU.W (A5),D5

;===========================================

divu_w_x_not_affected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_x_not_affected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000002,$00030000,.arrange_mem_00030000
 dc.l $00000000

.arrange_mem_00030000
 dc.b $00,$05

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00000100,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $8A,$D5

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00010033,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 DIVU.W (A5),D5

;===========================================

divu_w_n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00010000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $0007 ; --ZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8A,$FC,$00,$02

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00008000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 DIVU.W #$0002,D5

;===========================================

divu_w_n_not_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_n_not_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$0000ffff,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8A,$FC,$00,$02

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00017fff,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 DIVU.W #$0002,D5

;===========================================

divu_w_z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00000000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000b ; -N-OC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8A,$FC,$00,$02

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00000000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 DIVU.W #$0002,D5

;===========================================

divu_w_z_not_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_z_not_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00000003,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $8A,$FC,$00,$02

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$00010001,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 DIVU.W #$0002,D5

;===========================================

divu_w_v_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_v_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$00400000,$000000d4,$00000000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $86,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$00400000,$000000d4,$00000000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0002 ; SR=---O-

.assert_code
 DIVU.W D0,D3

;===========================================

divu_w_v_not_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_v_not_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000041,$000000d1,$555555d2,$00400000,$000000d4,$00010001,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $0007 ; --ZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $86,$C0

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000041,$000000d1,$555555d2,$0031fc0f,$000000d4,$00010001,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 DIVU.W D0,D3

;===========================================

divu_w_c_not_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "divu_w_c_not_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000041,$000000d1,$555555d2,$00400000,$000000d4,$00010001,$000000d6,$00000001
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $8E,$C7

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000041,$000000d1,$555555d2,$00400000,$000000d4,$00010001,$000000d6,$00000001
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$00030000,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 DIVU.W D7,D7

