; ----------------------T----------------------------------

; Path: ..\ami-test-runner\src\tests\eor.s
; This file is autogenerated

 ;rts in case this source is run by mistake
 rts

;===========================================

eor_l__data_register_to_ea__x_unaffected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__x_unaffected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000005,$00034440,.arrange_mem_00034440
 dc.l $00000000

.arrange_mem_00034440
 dc.b $11,$11,$11,$11,$11
 even

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$00034340,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $001c ; ENZ--

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $B3,$A9,$01,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000004,$00034440,.assert_mem_00034440
 dc.l $00000000

.assert_mem_00034440
 dc.b $25,$25,$25,$25

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$00034340,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040004 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 EOR.L D1,($0100,A1)

;===========================================

eor_l__data_register_to_ea__x_unaffected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__x_unaffected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000004,$00034440,.arrange_mem_00034440
 dc.l $00000000

.arrange_mem_00034440
 dc.b $11,$11,$11,$11

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$00034340,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000c ; -NZ--

.arrange_code
 ;length,address
 dc.l $00000002,$00040000
 dc.b $B3,$A9,$01,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000004,$00034440,.assert_mem_00034440
 dc.l $00000000

.assert_mem_00034440
 dc.b $25,$25,$25,$25

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$00034340,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040004 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.L D1,($0100,A1)

;===========================================

eor_l__data_register_to_ea__n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$80808080,$40404040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$86

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$80808080,$c0c0c0c0,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EOR.L D5,D6

;===========================================

eor_l__data_register_to_ea__n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0008 ; -N---

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$86

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$03030303,$41414141,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.L D5,D6

;===========================================

eor_l__data_register_to_ea__z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$90909090,$56565656,$78787878,$90909090,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000b ; -N-OC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B9,$81

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$00000000,$56565656,$78787878,$90909090,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 EOR.L D4,D1

;===========================================

eor_l__data_register_to_ea__z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$91909090,$56565656,$78787878,$90909090,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B9,$81

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$01000000,$56565656,$78787878,$90909090,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.L D4,D1

;===========================================

eor_l__data_register_to_ea__vc_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_l__data_register_to_ea__vc_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$91909090,$56565656,$78787878,$90009001,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0003 ; ---OC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B9,$81

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$01900091,$56565656,$78787878,$90009001,$03030303,$42424242,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.L D4,D1

;===========================================

eor_w__data_register_to_ea__x_unaffected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__x_unaffected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $001f ; ENZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BF,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcd2222,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 EOR.W D7,D6

;===========================================

eor_w__data_register_to_ea__x_unaffected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__x_unaffected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcdcdcd,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BF,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abababab,$cdcd2222,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.W D7,D6

;===========================================

eor_w__data_register_to_ea__n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab000c,$cdcdc00c,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0007 ; --ZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab000c,$cdcdc000,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EOR.W D5,D6

;===========================================

eor_w__data_register_to_ea__n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab800c,$cdcdc00c,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab800c,$cdcd4000,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.W D5,D6

;===========================================

eor_w__data_register_to_ea__z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc00c,$cdcdc00c,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0008 ; -N---

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc00c,$cdcd0000,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 EOR.W D5,D6

;===========================================

eor_w__data_register_to_ea__z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab8004,$cdcdc00c,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$abab8004,$cdcd4008,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.W D5,D6

;===========================================

eor_w__data_register_to_ea__vc_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_w__data_register_to_ea__vc_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababffff,$cdcdc33c,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000f ; -NZOC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$46

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababffff,$cdcd3cc3,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.W D5,D6

;===========================================

eor_b__data_register_to_ea__x_unaffected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__x_unaffected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0010 ; E----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B7,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $1212126a,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0010 ; SR=E----

.assert_code
 EOR.B D3,D0

;===========================================

eor_b__data_register_to_ea__x_unaffected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__x_unaffected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B7,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $1212126a,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.B D3,D0

;===========================================

eor_b__data_register_to_ea__n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$06

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc0c0,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EOR.B D5,D6

;===========================================

eor_b__data_register_to_ea__n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc0c0,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0008 ; -N---

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$06

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.B D5,D6

;===========================================

eor_b__data_register_to_ea__z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787812,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B7,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121200,$34343434,$56565656,$78787812,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 EOR.B D3,D0

;===========================================

eor_b__data_register_to_ea__z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121232,$34343434,$56565656,$78787813,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $0004 ; --Z--

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $B7,$00

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121221,$34343434,$56565656,$78787813,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EOR.B D3,D0

;===========================================

eor_b__data_register_to_ea__vc_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "eor_b__data_register_to_ea__vc_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc040,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.w $000b ; -N-OC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $BB,$06

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $12121212,$34343434,$56565656,$78787878,$90909090,$ababc080,$cdcdc0c0,$efefefef
 dc.l $21212121,$43434343,$65656565,$87878787,$09090909,$babababa,$dcdcdcdc,$fefefefe
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EOR.B D5,D6

