; ----------------------T----------------------------------

; Path: ..\ami-test-runner\src\tests\ext.s
; This file is autogenerated

 ;rts in case this source is run by mistake
 rts

;===========================================

ext_w_x_not_affected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_x_not_affected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0010 ; E----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$82

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$5555ffd2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0018 ; SR=EN---

.assert_code
 EXT.W D2

;===========================================

ext_w_x_not_affected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_x_not_affected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555d2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$82

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$5555ffd2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EXT.W D2

;===========================================

ext_w_n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$82

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$5555fff2,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EXT.W D2

;===========================================

ext_w_n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55555572,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0008 ; -N---

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$82

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55550072,$000000d3,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.W D2

;===========================================

ext_w_z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55555500,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$85

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55550000,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 EXT.W D5

;===========================================

ext_w_z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55555572,$000000d3,$000000d4,$55555501,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0004 ; --Z--

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$85

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55555572,$000000d3,$000000d4,$55550001,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.W D5

;===========================================

ext_w_vc_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_w_vc_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55555511,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0003 ; ---OC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$85

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55550011,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.W D5

;===========================================

ext_l_x_not_affected_still_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_x_not_affected_still_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$000000d2,$5555ddd2,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0010 ; E----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C3

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$000000d2,$ffffddd2,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0018 ; SR=EN---

.assert_code
 EXT.L D3

;===========================================

ext_l_x_not_affected_still_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_x_not_affected_still_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$000000d2,$5555ddd2,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C3

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$000000d2,$ffffddd2,$000000d4,$000000d5,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EXT.L D3

;===========================================

ext_l_n_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_n_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$0000d2d2,$5555d5f2,$000000d4,$000000d5,$000000d6,$d7d7d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C3

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$0000d2d2,$ffffd5f2,$000000d4,$000000d5,$000000d6,$d7d7d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0008 ; SR=-N---

.assert_code
 EXT.L D3

;===========================================

ext_l_n_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_n_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$0000d2d2,$555577d7,$000000d4,$000000d5,$000000d6,$d7d7d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0008 ; -N---

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C3

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$0000d2d2,$000077d7,$000000d4,$000000d5,$000000d6,$d7d7d7d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.L D3

;===========================================

ext_l_z_set
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_z_set",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$d50000d5,$000000d6,$55550000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0000 ; -----

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C7

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$d50000d5,$000000d6,$00000000
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0004 ; SR=--Z--

.assert_code
 EXT.L D7

;===========================================

ext_l_z_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_z_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55555572,$000000d3,$000000d4,$55555501,$000000d6,$555500d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0004 ; --Z--

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C7

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$55555572,$000000d3,$000000d4,$55555501,$000000d6,$000000d7
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.L D7

;===========================================

ext_l_vc_clear
 dc.l .name	; $00
 dc.l .arrange_mem	; $04
 dc.l .arrange_regs	; $08
 dc.l .arrange_code	; $0c
 dc.l .assert_mem	; $10
 dc.l .assert_regs	; $14
 dc.l .assert_code	; $18

.name
 dc.b "ext_l_vc_clear",0
 even

.arrange_mem
 ;length,address,ptr
 dc.l $00000000

.arrange_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55555511,$000000d6,$55555511
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.w $0003 ; ---OC

.arrange_code
 ;length,address
 dc.l $00000001,$00040000
 dc.b $48,$C7

.assert_mem
 ;length,address,ptr
 dc.l $00000000

.assert_regs
 ;    D0/A0     D1/A1     D2/A2     D3/A3     D4/A4     D5/A5     D6/A6     D7/A7
 dc.l $00000040,$000000d1,$555555f2,$000000d3,$000000d4,$55555511,$000000d6,$00005511
 dc.l $000000a0,$000000a1,$000000a2,$000000a3,$000000a4,$000000a5,$000000a6,$000000a7
 dc.l $00040002 ; PC
 dc.w $0000 ; SR=-----

.assert_code
 EXT.L D7

