;---------------T---------T---------------------T----------\x10
; Path: ..\ami-test-runner\src\tests\test_suite.s
; This file is autogenerated

	; rts in case this source is run by mistake
	rts

test_suite
	dc.l	address_register_indirect_to_data_register_direct_byte
	dc.l	address_register_indirect_to_data_register_direct_byte_overflow
	dc.l	address_register_indirect_to_data_register_direct_byte_carry
	dc.l	address_register_indirect_to_data_register_direct_word
	dc.l	address_register_indirect_to_data_register_direct_word_overflow
	dc.l	address_register_indirect_to_data_register_direct_word_carry
	dc.l	data_register_direct_to_data_register_direct_long
	dc.l	data_register_direct_to_address_register_indirect_long
	dc.l	data_register_direct_to_address_register_indirect_word
	dc.l	data_register_direct_to_address_register_indirect_byte
	dc.l	immediate_data_to_address_register_direct_word
	dc.l	immediate_data_to_address_register_direct_long
	dc.l	addi_byte_immediate_data_to_data_register_direct
	dc.l	addi_byte_immediate_data_to_absolute_short
	dc.l	addi_word_immediate_data_to_data_register_direct
	dc.l	addi_word_immediate_data_to_absolute_long
	dc.l	addi_long_immediate_data_to_data_register_direct
	dc.l	addi_long_immediate_data_to_absolute_long
	dc.l	addq_data_to_data_register_direct_byte
	dc.l	addq_data_to_data_register_direct_byte_overflow
	dc.l	addq_data_to_data_register_direct_word
	dc.l	addq_data_to_data_register_direct_word_carry
	dc.l	addq_data_to_data_register_direct_word_negative
	dc.l	addq_data_to_data_register_direct_long
	dc.l	addq_data_to_data_register_direct_long_zero
	dc.l	addq_data_to_address_register_direct_word
	dc.l	addq_data_to_address_register_direct_long
	dc.l	lsl_b_register_by_immediate
	dc.l	lsl_register_by_immediate_byte_negative
	dc.l	lsl_register_by_immediate_byte_zero
	dc.l	lsl_register_by_immediate_byte_extend_carry
	dc.l	lsl_register_by_immediate_word

	dc.l	$0

	include	"add.s"
	include	"addi.s"
	include	"addq.s"
	include	"lslr.s"
