// Path: ..\src\cpu\instruction\gen_tests.rs
// This file is autogenerated

pub mod add;
pub mod addi;
pub mod addq;
pub mod addx;
pub mod aslr;
pub mod divs;
pub mod divu;
pub mod eor;
pub mod ext;
pub mod jmp;
pub mod lslr;

